fix ARGS var building

diff --git a/bin/out b/bin/out
--- a/bin/out
+++ b/bin/out
@@ -26,13 +26,25 @@ for PROVISIONER_FILE in $PROVISIONER_FILES; do
   echo "Adding provisioner file $SRC/$PROVISIONER_FILE"
 done
 
+# ARGS=""
+# for var in $(jq -r '.params.vars | keys[] | @base64 // empty' /tmp/input); do
+#   KEY=$(echo ${var} | base64 -d)
+#   VALUE=$(jq -r .params.vars.${KEY} /tmp/input)
+#   ARGS="$ARGS -var='$KEY=$VALUE'"
+#   echo "Setting variable $KEY=$VALUE"
+# done
+
+
+# ARGS=$(jq -r '.params.vars | to_entries[] | "-var \(.key)=\(.value) \\"' /tmp/input)
+
 ARGS=""
-for var in $(jq -r '.params.vars | keys[] | @base64 // empty' /tmp/input); do
-  KEY=$(echo ${var} | base64 -d)
-  VALUE=$(jq -r .params.vars.${KEY} /tmp/input)
-  ARGS="$ARGS -var='$KEY=$VALUE'"
+for var in $(jq '.params.vars | to_entries[] | @base64 // empty' /tmp/input); do
+  KEY=$(echo ${var} | base64 -d | jq -r '.key')
+  VALUE=$(echo ${var} | base64 -d | jq -r '.value')
+  ARGS='$ARGS -var "$KEY=$VALUE"'
   echo "Setting variable $KEY=$VALUE"
 done
+
 
 # jq '.params|del(.template,provisioner_files,.var_files) // empty' /tmp/input > /tmp/vars.json
 
@@ -42,30 +54,38 @@ done
 #   ARGS="$ARGS -var='$VAR'"
 # done
 
-# VAR_FILES=$(jq -r '.params.var_files // empty | if type =="array" then .[] else . end' /tmp/input)
-# for VAR_FILE in $VAR_FILES; do
-#   if [ ! -f "$SRC/$VAR_FILE" ]; then
-#     echo "var_file $SRC/$VAR_FILE not found" >&2
-#     exit 1
-#   else
-#     ARGS="$ARGS -var-file=$SRC/$VAR_FILE"
-#   fi
-# done
+VAR_FILES=$(jq -r '.params.var_files // empty | if type =="array" then .[] else . end' /tmp/input)
+for VAR_FILE in $VAR_FILES; do
+  if [ ! -f "$SRC/$VAR_FILE" ]; then
+    echo "var_file $SRC/$VAR_FILE not found" >&2
+    exit 1
+  else
+    ARGS="$ARGS -var-file=$SRC/$VAR_FILE"
+  fi
+done
 
 # jq '.params|del(.template,.var_file) // empty' /tmp/input > /tmp/vars.json
 
 cd $(dirname $SRC/$TEMPLATE)
 
-echo
-echo "Running: packer validate $ARGS $SRC/$TEMPLATE"
-packer validate $ARGS $SRC/$TEMPLATE
+# echo
+# echo "Running: packer validate $ARGS $SRC/$TEMPLATE"
+# packer validate $ARGS $SRC/$TEMPLATE
 # packer validate $ARGS -var-file=/tmp/vars.json $SRC/$TEMPLATE
 
-echo
-echo "Running: packer build -machine-readable $ARGS $SRC/$TEMPLATE | tee /tmp/output | awk -F, '/,ui,/ { print $5 }' | sed -u 's#%!(PACKER_COMMA)#,#g;s#\\n#\n#g'"
-packer build -machine-readable $ARGS $SRC/$TEMPLATE \
+# echo
+# echo "Running: packer build -machine-readable $ARGS $SRC/$TEMPLATE"
+# packer build -machine-readable $(ARGS) $SRC/$TEMPLATE
+
+echo "#!/bin/sh" >/tmp/cmd
+echo "packer build -machine-readable $ARGS $SRC/$TEMPLATE" >>/tmp/cmd
+chmod a+x /tmp/cmd
+/tmp/cmd
+# $(echo "packer build -machine-readable $(ARGS) $SRC/$TEMPLATE")
+
+# | tee /tmp/output
 # packer build -machine-readable $ARGS -var-file=/tmp/vars.json $SRC/$TEMPLATE \
-  | tee /tmp/output | awk -F, '/,ui,/ { print $5 }' | sed -u 's#%!(PACKER_COMMA)#,#g;s#\\n#\n#g'
+#  | awk -F, '/,ui,/ { print $5 }' | sed -u 's#%!(PACKER_COMMA)#,#g;s#\\n#\n#g'
 
 IMAGE=$(awk -F: '/artifact,0,id/ { print $2 }' /tmp/output)
 echo "image: $IMAGE"
